import {
  Activity,
  Anchor,
  Apple,
  Archive,
  Award,
  Backpack,
  Banknote,
  BarChart3,
  Beaker,
  Bell,
  Bike,
  Book,
  BookOpen,
  Bookmark,
  Brain,
  Briefcase,
  Brush,
  Building,
  Cake,
  Calendar,
  Camera,
  Car,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  Dumbbell,
  Feather,
  Film,
  Flag,
  Flame,
  Flower,
  Folder,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  Home,
  Image,
  Inbox,
  Key,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Map,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Package,
  PaintBucket,
  Palette,
  PenTool,
  PiggyBank,
  Pizza,
  Plane,
  Puzzle,
  Rocket,
  Scissors,
  Settings,
  Shield,
  ShoppingCart,
  Smile,
  Sparkles,
  Star,
  Sun,
  Target,
  Tent,
  Terminal,
  ThumbsUp,
  Trees,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Wand,
  Watch,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

// Curated set of friendly, recognisable icons for projects/lists/areas.
// Keys are stable string identifiers stored in the database.
export const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  anchor: Anchor,
  apple: Apple,
  archive: Archive,
  award: Award,
  backpack: Backpack,
  banknote: Banknote,
  "bar-chart": BarChart3,
  beaker: Beaker,
  bell: Bell,
  bike: Bike,
  book: Book,
  "book-open": BookOpen,
  bookmark: Bookmark,
  brain: Brain,
  briefcase: Briefcase,
  brush: Brush,
  building: Building,
  cake: Cake,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  cpu: Cpu,
  "credit-card": CreditCard,
  crown: Crown,
  database: Database,
  diamond: Diamond,
  dumbbell: Dumbbell,
  feather: Feather,
  film: Film,
  flag: Flag,
  flame: Flame,
  flower: Flower,
  folder: Folder,
  gamepad: Gamepad2,
  gift: Gift,
  globe: Globe,
  graduation: GraduationCap,
  hammer: Hammer,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  image: Image,
  inbox: Inbox,
  key: Key,
  laptop: Laptop,
  layers: Layers,
  leaf: Leaf,
  lightbulb: Lightbulb,
  map: Map,
  message: MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  package: Package,
  "paint-bucket": PaintBucket,
  palette: Palette,
  pen: PenTool,
  "piggy-bank": PiggyBank,
  pizza: Pizza,
  plane: Plane,
  puzzle: Puzzle,
  rocket: Rocket,
  scissors: Scissors,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  tent: Tent,
  terminal: Terminal,
  "thumbs-up": ThumbsUp,
  trees: Trees,
  trending: TrendingUp,
  trophy: Trophy,
  tv: Tv,
  umbrella: Umbrella,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wand: Wand,
  watch: Watch,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
};

export const ICON_KEYS = Object.keys(ICON_MAP);

export function resolveIcon(name: string | null | undefined, fallback: LucideIcon): LucideIcon {
  if (!name) return fallback;
  return ICON_MAP[name] ?? fallback;
}
